Repository sendgrid/python-http-client, pull requests merged in 2018-05, with the labels that each got.

#73 Add CodeCov support to .travis.yml
  .travis.yml
Labels: difficulty: easy, hacktoberfest, status: code review request, type: sendgrid enhancement

#77 include code reviews section Fixes #76
  CONTRIBUTING.md
  README.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: docs update

#82 Fix #80
  tests/test_unit.py
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement

#83 Fix travis build errors
  USE_CASES.md
Labels: difficulty: easy, status: code review request, type: bug, type: docs update

#84 Fix docstring variable name
  python_http_client/client.py
Labels: difficulty: easy, status: code review request, type: bug, type: docs update

#87 Add manifest that includes the license in sdist
  MANIFEST.in
Labels: status: waiting for feedback
