Repository sendgrid/python-http-client, pull requests merged in 2018-10, with the labels that each got.

#91 Add support for Python 3.7
  .travis.yml
  CONTRIBUTING.md
  Dockerfile
  tox.ini
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#96 Create a use cases directory 🎃
  USE_CASES.md
  tests/test_repofiles.py
  use_cases/README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#93 converted README and version as file
  .gitignore
  MANIFEST.in
  README.md
  README.rst
  VERSION.txt
  python_http_client/__init__.py
  register.py
  setup.cfg
  setup.py
  tests/test_repofiles.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: community enhancement

#104 Add first-timers.md file for newcomers
  first-timers.md
  static/img/github-fork.png
  static/img/github-signup.png
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#105 add missed Python 3.7 classifier
  setup.py
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#107 Update CONTRIBUTING - contribution guideline to branch off development
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#111 String Formatting and PEP-8 fixes
  python_http_client/client.py
  tests/test_repofiles.py
  tests/test_unit.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement
