Repository sendgrid/python-http-client, pull requests merged in 2019-09, with the labels that each got.

#120 Fix a year in LICENSE.txt file to fix test__daterange.
  LICENSE.txt
Labels: difficulty: easy, status: ready for deploy, type: bug

#122 Let test_datarange show only a warning instead of fail on AssertionError
  tests/test_daterange.py
Labels: status: ready for deploy

#124 Twilio branding and CLA policy update
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  LICENSE.txt
  README.rst
  first-timers.md
  tests/test_daterange.py
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement
